# docker-compose.yml
version: '3'

services:
  database:
    image: "postgres"
    restart: always
    env_file:
     - api.env
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}
     - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    volumes:
      - pg-api-data:/var/lib/pgapi/data/ # persist data even if container shuts down
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - main-network

  server: 
    build: .
    networks:
      - main-network
    environment:
      db_connection_url: "postgresql://admin:admin@database:5432/pg1"
    depends_on:
      - database
    ports:
      - "1234:1234"


volumes:
  pg-api-data: # named volumes can be managed easier using docker-compose


networks:
  main-network:
    driver: "bridge"
